version: '3.8'

services:
  backend:
    build: ./flowsint-api
    ports:
      - "5000:5000"
    volumes:
      - ./flowsint-api:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./flowsint-web
    ports:
      - "3000:3000"
    volumes:
      - ./flowsint-web:/app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
