from pydantic import BaseModel, Field
from typing import Optional, List
from .individual import Individual
from .address import PhysicalAddress

class Organization(BaseModel):
    # Basic information
    name: str = Field(..., description="Organization name")
    siren: Optional[str] = Field(None, description="SIREN number")
    nom_complet: Optional[str] = Field(None, description="Complete name")
    nom_raison_sociale: Optional[str] = Field(None, description="Company name")
    sigle: Optional[str] = Field(None, description="Acronym")
    # Establishment information
    nombre_etablissements: Optional[int] = Field(None, description="Number of establishments")
    nombre_etablissements_ouverts: Optional[int] = Field(None, description="Number of open establishments")
    # Activity information
    activite_principale: Optional[str] = Field(None, description="Main activity code")
    section_activite_principale: Optional[str] = Field(None, description="Main activity section")
    # Company category
    categorie_entreprise: Optional[str] = Field(None, description="Company category")
    annee_categorie_entreprise: Optional[str] = Field(None, description="Year of company category")
    # Employment information
    caractere_employeur: Optional[str] = Field(None, description="Employer character")
    tranche_effectif_salarie: Optional[str] = Field(None, description="Employee size range")
    annee_tranche_effectif_salarie: Optional[str] = Field(None, description="Year of employee size range")
    # Dates
    date_creation: Optional[str] = Field(None, description="Creation date")
    date_fermeture: Optional[str] = Field(None, description="Closing date")
    date_mise_a_jour: Optional[str] = Field(None, description="Update date")
    date_mise_a_jour_insee: Optional[str] = Field(None, description="INSEE update date")
    date_mise_a_jour_rne: Optional[str] = Field(None, description="RNE update date")
    # Legal information
    nature_juridique: Optional[str] = Field(None, description="Legal nature")
    etat_administratif: Optional[str] = Field(None, description="Administrative status")
    statut_diffusion: Optional[str] = Field(None, description="Diffusion status")
    # Siege (Headquarters) information
    siege_activite_principale: Optional[str] = Field(None, description="Siege main activity code")
    siege_activite_principale_registre_metier: Optional[str] = Field(None, description="Siege main activity in trade register")
    siege_annee_tranche_effectif_salarie: Optional[str] = Field(None, description="Siege year of employee size range")
    siege_adresse: Optional[str] = Field(None, description="Siege address")
    siege_caractere_employeur: Optional[str] = Field(None, description="Siege employer character")
    siege_cedex: Optional[str] = Field(None, description="Siege CEDEX code")
    siege_code_pays_etranger: Optional[str] = Field(None, description="Siege foreign country code")
    siege_code_postal: Optional[str] = Field(None, description="Siege postal code")
    siege_commune: Optional[str] = Field(None, description="Siege municipality code")
    siege_complement_adresse: Optional[str] = Field(None, description="Siege address complement")
    siege_coordonnees: Optional[str] = Field(None, description="Siege coordinates")
    siege_date_creation: Optional[str] = Field(None, description="Siege creation date")
    siege_date_debut_activite: Optional[str] = Field(None, description="Siege activity start date")
    siege_date_fermeture: Optional[str] = Field(None, description="Siege closing date")
    siege_date_mise_a_jour: Optional[str] = Field(None, description="Siege update date")
    siege_date_mise_a_jour_insee: Optional[str] = Field(None, description="Siege INSEE update date")
    siege_departement: Optional[str] = Field(None, description="Siege department code")
    siege_distribution_speciale: Optional[str] = Field(None, description="Siege special distribution")
    siege_epci: Optional[str] = Field(None, description="Siege EPCI code")
    siege_est_siege: Optional[bool] = Field(None, description="Siege is headquarters")
    siege_etat_administratif: Optional[str] = Field(None, description="Siege administrative status")
    siege_geo_adresse: Optional[PhysicalAddress] = Field(None, description="Siege geocoded address")
    siege_geo_id: Optional[str] = Field(None, description="Siege geographic ID")
    siege_indice_repetition: Optional[str] = Field(None, description="Siege repetition index")
    siege_latitude: Optional[str] = Field(None, description="Siege latitude")
    siege_libelle_cedex: Optional[str] = Field(None, description="Siege CEDEX label")
    siege_libelle_commune: Optional[str] = Field(None, description="Siege municipality label")
    siege_libelle_commune_etranger: Optional[str] = Field(None, description="Siege foreign municipality label")
    siege_libelle_pays_etranger: Optional[str] = Field(None, description="Siege foreign country label")
    siege_libelle_voie: Optional[str] = Field(None, description="Siege street label")
    siege_liste_enseignes: Optional[List[str]] = Field(None, description="Siege list of brands")
    siege_liste_finess: Optional[List[str]] = Field(None, description="Siege list of FINESS")
    siege_liste_id_bio: Optional[List[str]] = Field(None, description="Siege list of bio IDs")
    siege_liste_idcc: Optional[List[str]] = Field(None, description="Siege list of IDCC")
    siege_liste_id_organisme_formation: Optional[List[str]] = Field(None, description="Siege list of training organization IDs")
    siege_liste_rge: Optional[List[str]] = Field(None, description="Siege list of RGE")
    siege_liste_uai: Optional[List[str]] = Field(None, description="Siege list of UAI")
    siege_longitude: Optional[str] = Field(None, description="Siege longitude")
    siege_nom_commercial: Optional[str] = Field(None, description="Siege commercial name")
    siege_numero_voie: Optional[str] = Field(None, description="Siege street number")
    siege_region: Optional[str] = Field(None, description="Siege region code")
    siege_siret: Optional[str] = Field(None, description="Siege SIRET number")
    siege_statut_diffusion_etablissement: Optional[str] = Field(None, description="Siege establishment diffusion status")
    siege_tranche_effectif_salarie: Optional[str] = Field(None, description="Siege employee size range")
    siege_type_voie: Optional[str] = Field(None, description="Siege street type")
    # Dirigeants (Leaders) - using Individual type
    dirigeants: Optional[List[Individual]] = Field(None, description="List of leaders")
    # Matching establishments
    matching_etablissements: Optional[List[dict]] = Field(None, description="Matching establishments")
    # Financial information
    finances: Optional[dict] = Field(None, description="Financial information")
    # Complements (Additional information)
    complements_collectivite_territoriale: Optional[str] = Field(None, description="Complements territorial community")
    complements_convention_collective_renseignee: Optional[bool] = Field(None, description="Complements collective agreement informed")
    complements_liste_idcc: Optional[List[str]] = Field(None, description="Complements list of IDCC")
    complements_egapro_renseignee: Optional[bool] = Field(None, description="Complements Egapro informed")
    complements_est_achats_responsables: Optional[bool] = Field(None, description="Complements is responsible purchases")
    complements_est_alim_confiance: Optional[bool] = Field(None, description="Complements is food trust")
    complements_est_association: Optional[bool] = Field(None, description="Complements is association")
    complements_est_bio: Optional[bool] = Field(None, description="Complements is bio")
    complements_est_entrepreneur_individuel: Optional[bool] = Field(None, description="Complements is individual entrepreneur")
    complements_est_entrepreneur_spectacle: Optional[bool] = Field(None, description="Complements is show entrepreneur")
    complements_est_ess: Optional[bool] = Field(None, description="Complements is ESS")
    complements_est_finess: Optional[bool] = Field(None, description="Complements is FINESS")
    complements_est_organisme_formation: Optional[bool] = Field(None, description="Complements is training organization")
    complements_est_qualiopi: Optional[bool] = Field(None, description="Complements is Qualiopi")
    complements_liste_id_organisme_formation: Optional[List[str]] = Field(None, description="Complements list of training organization IDs")
    complements_est_rge: Optional[bool] = Field(None, description="Complements is RGE")
    complements_est_service_public: Optional[bool] = Field(None, description="Complements is public service")
    complements_est_l100_3: Optional[bool] = Field(None, description="Complements is L100-3")
    complements_est_siae: Optional[bool] = Field(None, description="Complements is SIAE")
    complements_est_societe_mission: Optional[bool] = Field(None, description="Complements is mission company")
    complements_est_uai: Optional[bool] = Field(None, description="Complements is UAI")
    complements_est_patrimoine_vivant: Optional[bool] = Field(None, description="Complements is living heritage")
    complements_bilan_ges_renseigne: Optional[bool] = Field(None, description="Complements GES balance informed")
    complements_identifiant_association: Optional[str] = Field(None, description="Complements association identifier")
    complements_statut_entrepreneur_spectacle: Optional[str] = Field(None, description="Complements show entrepreneur status")
    complements_type_siae: Optional[str] = Field(None, description="Complements SIAE type")