import {
    Activity,
    ArrowRightLeft,
    AtSign,
    Bike,
    Bitcoin,
    Building2,
    Calendar,
    Camera,
    Car,
    CreditCard,
    DollarSign,
    Facebook,
    FileIcon,
    Fingerprint,
    Footprints,
    Ghost,
    Github,
    Globe,
    GraduationCap,
    ImageIcon,
    Instagram,
    Key,
    Laptop,
    Linkedin,
    Locate,
    MapPin,
    MessageCircle,
    MessageCircleDashed,
    MessageSquare,
    Phone,
    Plane,
    Sailboat,
    Send,
    ShoppingCart,
    Smartphone,
    Tablet,
    Twitch,
    Twitter,
    User,
    Users,
    Video,
    Wifi,
    type LucideIcon,
} from "lucide-react"

// Enhanced ActionItem type that includes fields from nodesTypes
export type ActionItem = {
    id: number
    type: string
    table: string
    icon: LucideIcon
    color?: string
    label: string
    key: string,
    fields: string[]
    disabled?: boolean
    comingSoon?: boolean
    children?: ActionItem[]
}

export const actionItems: ActionItem[] = [
    {
        id: 1,
        type: "individual",
        table: "individuals",
        key: "individuals",
        icon: User,
        label: "New relation",
        fields: ["full_name"],
    },
    {
        id: 2,
        type: "phone",
        table: "phone_numbers",
        key: "phone_numbers",
        icon: Phone,
        label: "Phone number",
        fields: ["phone_number"],
    },
    {
        id: 3,
        type: "address",
        table: "physical_addresses",
        key: "physical_addresses",
        icon: MapPin,
        label: "Physical address",
        fields: ["address", "city", "country", "zip"],
    },
    {
        id: 4,
        type: "email",
        table: "emails",
        key: "emails",
        icon: AtSign,
        label: "Email address",
        fields: ["email"],
    },
    {
        id: 5,
        type: "ip",
        table: "ip_addresses",
        key: "ip_addresses",
        icon: Locate,
        label: "IP address",
        fields: ["ip_address"],
    },
    {
        id: 6,
        type: "social_account",
        table: "",
        key: "social_account",
        icon: Send,
        label: "Social account",
        fields: [],
        children: [
            {
                id: 7,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_facebook",
                icon: Facebook,
                color: "#1d4ed8",
                label: "Facebook",
                fields: ["profile_url", "username", "platform:facebook"],
            },
            {
                id: 8,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_instagram",
                icon: Instagram,
                color: "#db2777",
                label: "Instagram",
                fields: ["profile_url", "username", "platform:instagram"],
            },
            {
                id: 9,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_telegram",
                icon: Send,
                color: "#0369a1",
                label: "Telegram",
                fields: ["profile_url", "username", "platform:telegram"],
            },
            {
                id: 10,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_signal",
                icon: MessageCircleDashed,
                color: "#3B45FC",
                label: "Signal",
                fields: ["profile_url", "username", "platform:signal"],
            },
            {
                id: 11,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_snapchat",
                color: "#FEFC00",
                icon: Ghost,
                label: "Snapchat",
                fields: ["profile_url", "username", "platform:snapchat"],
            },
            {
                id: 12,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_github",
                icon: Github,
                label: "Github",
                fields: ["profile_url", "username", "platform:github"],
            },
            {
                id: 13,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_coco",
                icon: Send,
                label: "Coco",
                fields: ["profile_url", "username", "platform:coco"],
                disabled: true,
                comingSoon: true,
            },
            {
                id: 18,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_linkedin",
                color: "#116AC9",
                icon: Linkedin,
                label: "LinkedIn",
                fields: ["profile_url", "username", "platform:linkedin"],
            },
            {
                id: 19,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_twitter",
                icon: Twitter,
                label: "Twitter",
                fields: ["profile_url", "username", "platform:twitter"],
            },
            {
                id: 20,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_tiktok",
                icon: Video,
                label: "TikTok",
                fields: ["profile_url", "username", "platform:tiktok"],
            },
            {
                id: 21,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_reddit",
                icon: MessageSquare,
                color: "#FF4B13",
                label: "Reddit",
                fields: ["profile_url", "username", "platform:reddit"],
            },
            {
                id: 22,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_discord",
                icon: MessageCircle,
                color: "#525FEE",
                label: "Discord",
                fields: ["profile_url", "username", "platform:discord"],
            },
            {
                id: 2343,
                type: "social",
                table: "social_accounts",
                key: "social_accounts_twitch",
                icon: Twitch,
                color: "#A96FFF",
                label: "Twitch",
                fields: ["profile_url", "username", "platform:twitch"],
            },
        ],
    },
    {
        id: 14,
        type: "vehicle",
        table: "",
        icon: Car,
        label: "Vehicle",
        key: "vehicle",
        fields: [],
        children: [
            {
                id: 15,
                type: "vehicle",
                table: "vehicles",
                key: "vehicles_car",
                icon: Car,
                label: "Car",
                fields: ["plate", "model", "brand", "year", "type:car"],
            },
            {
                id: 16,
                type: "vehicle",
                table: "vehicles",
                key: "vehicles_motorcycle",
                icon: Bike,
                label: "Motorcycle",
                fields: ["plate", "model", "brand", "year", "type:motorcycle"],
            },
            {
                id: 17,
                type: "vehicle",
                table: "vehicles",
                key: "vehicles_boat",
                icon: Sailboat,
                label: "Boat",
                fields: ["plate", "model", "brand", "year", "type:boat"],
            },
            {
                id: 23,
                type: "vehicle",
                table: "vehicles",
                key: "vehicles_aircraft",
                icon: Plane,
                label: "Aircraft",
                fields: ["registration", "model", "manufacturer", "year", "type:aircraft"],
            },
        ],
    },
    {
        id: 24,
        type: "organization",
        table: "organizations",
        key: "organizations",
        icon: Building2,
        label: "Organization",
        fields: ["name", "registration_number", "founding_date"],
    },
    {
        id: 25,
        type: "website",
        table: "websites",
        key: "websites",
        icon: Globe,
        label: "Website",
        fields: ["url", "registration_date", "registrar", "ip_address"],
    },
    {
        id: 26,
        type: "document",
        table: "documents",
        key: "documents",
        icon: FileIcon,
        label: "Document",
        fields: ["title", "author", "creation_date", "file_hash", "file_type"],
    },
    {
        id: 27,
        type: "financial",
        table: "",
        key: "financial",
        icon: DollarSign,
        label: "Financial",
        fields: [],
        children: [
            {
                id: 28,
                type: "financial",
                table: "crypto_wallets",
                key: "crypto_wallets",
                icon: Bitcoin,
                label: "Crypto Wallet",
                fields: ["address", "currency", "platform"],
            },
            {
                id: 29,
                type: "financial",
                table: "bank_accounts",
                key: "bank_accounts",
                icon: CreditCard,
                label: "Bank Account",
                fields: ["account_number", "bank_name", "iban", "bic"],
            },
            {
                id: 30,
                type: "financial",
                table: "transactions",
                key: "transactions",
                icon: ArrowRightLeft,
                label: "Transaction",
                fields: ["amount", "date", "sender", "recipient", "currency"],
            },
        ],
    },
    {
        id: 31,
        type: "event",
        table: "events",
        key: "events",
        icon: Calendar,
        label: "Event",
        fields: ["name", "date", "location", "description", "participants"],
    },
    {
        id: 32,
        type: "device",
        table: "",
        key: "device",
        icon: Smartphone,
        label: "Device",
        fields: [],
        children: [
            {
                id: 33,
                type: "device",
                table: "devices",
                key: "devices_phone",
                icon: Smartphone,
                label: "Phone",
                fields: ["imei", "model", "manufacturer", "serial_number", "type:phone"],
            },
            {
                id: 34,
                type: "device",
                table: "devices",
                key: "devices_computer",
                icon: Laptop,
                label: "Computer",
                fields: ["mac_address", "model", "manufacturer", "serial_number", "type:computer"],
            },
            {
                id: 35,
                type: "device",
                table: "devices",
                key: "devices_tablet",
                icon: Tablet,
                label: "Tablet",
                fields: ["imei", "model", "manufacturer", "serial_number", "type:tablet"],
            },
            {
                id: 36,
                type: "device",
                table: "devices",
                key: "devices_iot",
                icon: Wifi,
                label: "IoT Device",
                fields: ["mac_address", "model", "manufacturer", "serial_number", "type:iot"],
            },
        ],
    },
    {
        id: 37,
        type: "media",
        table: "media",
        key: "media",
        icon: ImageIcon,
        label: "Media",
        fields: ["filename", "hash", "creation_date", "location", "exif_data"],
    },
    {
        id: 38,
        type: "education",
        table: "education",
        key: "education",
        icon: GraduationCap,
        label: "Education",
        fields: ["institution", "degree", "field", "start_date", "end_date"],
    },
    {
        id: 39,
        type: "relationship",
        table: "relationships",
        key: "relationships",
        icon: Users,
        label: "Relationship",
        fields: ["type", "entity_a", "entity_b", "start_date", "end_date", "description"],
    },
    {
        id: 40,
        type: "online_activity",
        table: "",
        key: "online_activity",
        icon: Activity,
        label: "Online Activity",
        fields: [],
        children: [
            {
                id: 41,
                type: "online_activity",
                table: "forum_posts",
                key: "forum_posts",
                icon: MessageSquare,
                label: "Forum Post",
                fields: ["forum", "username", "post_date", "post_content", "post_url", "type:forum_post"],
            },
            {
                id: 42,
                type: "online_activity",
                table: "comments",
                key: "comments",
                icon: MessageCircle,
                label: "Comment",
                fields: ["platform", "username", "comment_date", "comment_content", "comment_url", "type:comment"],
            },
            {
                id: 43,
                type: "online_activity",
                table: "online_purchases",
                key: "online_purchases",
                icon: ShoppingCart,
                label: "Online Purchase",
                fields: ["platform", "username", "purchase_date", "item", "price", "type:purchase"],
            },
        ],
    },
    {
        id: 44,
        type: "digital_footprint",
        table: "digital_footprints",
        key: "digital_footprints",
        icon: Footprints,
        label: "Digital Footprint",
        fields: ["platform", "username", "date_discovered", "data_type", "source_url"],
    },
    {
        id: 45,
        type: "biometric",
        table: "biometric_data",
        key: "biometric_data",
        icon: Fingerprint,
        label: "Biometric Data",
        fields: ["type", "identifier", "date_collected", "source"],
    },
    {
        id: 46,
        type: "credential",
        table: "credentials",
        key: "credentials",
        icon: Key,
        label: "Credential",
        fields: ["service", "username", "hash", "breach_date", "breach_source"],
    },
]