services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["/app/entrypoint.sh", "app"]

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - app
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["/app/entrypoint.sh", "celery"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
